image: "estusdev/rust-ci:rust-wasm-1.69"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - build
  - test
  - deploy

build-crab8_frontend:
  stage: build
  before_script:
    - rustc --version
    - cargo --version
    # Install atk for rfd crate.
    - apt update
    - apt install librust-atk-dev
  script:
    - cargo build -p crab8_frontend --release
  artifacts:
    paths:
      - ./target/release/
    exclude:
      - ./target/release/.fingerprint/**/*
      - ./target/release/build/**/*
      - ./target/release/deps/**/*
      - ./target/release/examples/**/*
      - ./target/release/incremental/**/*
      - ./target/release/.cargo-lock
  cache:
    paths:
      - ./target/
    key: ${CI_COMMIT_REF_SLUG}-linux

build-crab8_frontend_wasm:
  stage: build
  script:
    - ./crates/crab8_frontend/scripts/build-wasm.sh
  artifacts:
    paths:
      - ./target/wasm32-unknown-unknown/release/
      - ./crates/crab8_frontend/wasm/assets/
      - ./crates/crab8_frontend/wasm/built/
    exclude:
      - ./target/wasm32-unknown-unknown/release/.fingerprint/**/*
      - ./target/wasm32-unknown-unknown/release/build/**/*
      - ./target/wasm32-unknown-unknown/release/deps/**/*
      - ./target/wasm32-unknown-unknown/release/examples/**/*
      - ./target/wasm32-unknown-unknown/release/incremental/**/*
      - ./target/wasm32-unknown-unknown/release/.cargo-lock
  cache:
    paths:
      - ./target/
    key: ${CI_COMMIT_REF_SLUG}-wasm

test-crab8:
  stage: test
  cache: []
  script:
    - cargo test

deploy-crab8_frontend_wasm:
  only:
    - main
  image:
    name: ghcr.io/williamjacksn/netlify-cli
    entrypoint: [""]
  stage: deploy
  cache: []
  before_script:
    - netlify --version
  script:
    - netlify deploy --prod --dir ./crates/crab8_frontend/wasm
