[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true, optional = true }
rand = { workspace = true }
reqwest = { workspace = true }

[features]
bevy = ["dep:bevy"]

[workspace]
members = ["crates/bevy_chip8"]

[workspace.dependencies]
bevy = "^0.10"
rand = "^0.8"
reqwest = { version = "^0.11.16", features = ["blocking"] }
